# Generated by Django 3.0.5 on 2020-05-13 20:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_on', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restapi.Project')),
            ],
        ),
    ]
